// <auto-generated />
namespace LojaWebEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Relacionamento_CategoriaProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relacionamento_CategoriaProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201512261240091_Relacionamento_Categoria-Produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
